services:
  - type: web
    name: expense-tracker
    env: python
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.9.0
    disk:
      name: data
      mountPath: /opt/render/project/src/data
      sizeGB: 1